name: prato_certo
description: "Aplicativo de controle de estoque e cardápio para restaurantes."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.8.3 # Necessário para o uso do banco local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Você pode descomentar e usar assets no futuro, se quiser imagens personalizadas.
  # assets:
  #   - assets/images/
